//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjo_user_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detail_user_japan
    {
        public int detail_user_japan_id { get; set; }
        public int user_id { get; set; }
        public string code_level { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int total { get; set; }
    
        public virtual mst_japan mst_japan { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
