//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjo_user_management.Models
{
    using prjo_user_management.utils;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_detail_user_japan = new HashSet<tbl_detail_user_japan>();
        }


        public int user_id { get; set; }
        public int group_id { get; set; }
        public string login_name { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string full_name_kana { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public System.DateTime birthday { get; set; }
        public string role { get; set; }
        public string salt { get; set; }
    
        public virtual mst_group mst_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detail_user_japan> tbl_detail_user_japan { get; set; }
    }
}
